name: Django Testing and Deploy

# Указываем при каких условиях срабатывает workflow
on:
  push:
    branches: [main]

#
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: admin
      POSTGRES_PASS: adminpass
      POSTGRES_HOST: postgresdb
      POSTGRES_PORT: 5432
      POSTGRES_DB: stocks
      SECRET_KEY: django-insecure-nw^y+m^wmxza1asgk+)!ua2qx9)g+#v=6%76-9i8i(6eqiw94j
      ALLOWED_HOSTS: ['*']
    services:
      postgres_main:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASS }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checking for Changes
        uses: actions/checkout@v2

      - name: Installation Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Installation requirements
        run: pip install -r requirements.txt

      - name: Code linting
        run: flake8 main

#       - name: Тестинг
#         run: python manage.py test
#         env:
#           SECRET_KEY: ${{ env.SECRET_KEY }}
#           DEBUG: "0"
#           ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
#           DB_ENGINE: django.db.backends.postgresql
#           DB_NAME: ${{ env.POSTGRES_DB }}
#           DB_USER: ${{ env.POSTGRES_USER }}
#           DB_PASSWORD: ${{ env.POSTGRES_PASS }}
#           DB_HOST: ${{ env.POSTGRES_HOST }}
#           DB_PORT: ${{ env.POSTGRES_PORT }}