# Generated by Django 4.1 on 2022-09-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='DRAFT',
            field=models.BooleanField(default=True),
        ),
    ]
