# Generated by Django 4.1 on 2022-09-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='DRAFT',
            field=models.BooleanField(default=False),
        ),
    ]
