# Generated by Django 4.1 on 2022-09-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='DRAFT',
            new_name='draft',
        ),
    ]
