# Generated by Django 4.1 on 2022-09-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_favorite_ad_alter_favorite_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='advertisements.advertisement'),
        ),
    ]
